# Generated by Django 3.2.5 on 2021-07-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkthrough',
            name='slide_images',
            field=models.ImageField(default='images/default.jpeg', upload_to='images/'),
        ),
    ]
